version: "3.7"

services:
  directus:
    image: directus/directus
    ports:
     - 8059:8055
    volumes:
      - .:/directus/extensions/directus-extension-o2m-map-interface
    environment:
      KEY: asdf
      SECRET: asdf
      ADMIN_EMAIL: a@a.co
      ADMIN_PASSWORD: admin
      PUBLIC_URL: "http://localhost:8055"
      EXTENSIONS_AUTO_RELOAD: "1"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

  postgres:
    image: postgis/postgis:16-3.5-alpine
    environment:
      POSTGRES_DB: "directus"
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
    volumes:
      - ./data:/var/lib/postgresql/data
